# Generated by Django 3.1.5 on 2021-01-09 20:09

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.CharField(max_length=255)),
                ('Tuesday', models.CharField(max_length=255)),
                ('Wednesday', models.CharField(max_length=255)),
                ('Thursday', models.CharField(max_length=255)),
                ('Friday', models.CharField(max_length=255)),
                ('Saturday', models.CharField(max_length=255)),
                ('Sunday', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mail', models.EmailField(max_length=254)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='theatreImage')),
                ('playsRating', models.IntegerField(default=-1, editable=False)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatres.workprogram')),
                ('theatreType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatretype')),
            ],
        ),
    ]
