# Generated by Django 3.1.5 on 2021-01-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogram',
            name='description',
            field=models.CharField(default='desctiption', max_length=255),
            preserve_default=False,
        ),
    ]
