# Generated by Django 3.1.5 on 2021-01-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0002_workprogram_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='program',
        ),
        migrations.AddField(
            model_name='theatre',
            name='website',
            field=models.CharField(default="", max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workprogram',
            name='theatre',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre'),
            preserve_default=False,
        ),
    ]
