# Generated by Django 3.1.5 on 2021-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_actorrole'),
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultplay',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='artists.ActorRole'),
        ),
    ]
