# Generated by Django 3.1.5 on 2021-01-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0004_auto_20210112_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultplay',
            name='actors',
        ),
    ]
