# Generated by Django 3.1.5 on 2021-01-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_remove_vaultplay_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultplay',
            name='writer',
            field=models.CharField(default='Writer Smecher', max_length=255),
            preserve_default=False,
        ),
    ]
