# Generated by Django 3.1.5 on 2021-01-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_remove_vaultplay_actors'),
        ('artists', '0002_actorrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorrole',
            name='vaultPlay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plays.vaultplay'),
            preserve_default=False,
        ),
    ]
