# Generated by Django 3.1.5 on 2021-01-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0006_vaultplay_writer'),
        ('theatres', '0003_auto_20210112_1429'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('artists', '0003_actorrole_vaultplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('artists', models.ManyToManyField(to='artists.Artist')),
                ('plays', models.ManyToManyField(to='plays.VaultPlay')),
                ('theatres', models.ManyToManyField(to='theatres.Theatre')),
            ],
        ),
    ]
